"""Add user_id to InventoryItem

Revision ID: 3f4a9ed94be5
Revises: b286167059b7
Create Date: 2025-05-10 17:00:31.754242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4a9ed94be5'
down_revision = 'b286167059b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_inventory_item_user_id',  # Explicit name for the foreign key
            'user',  # Referenced table
            ['user_id'],  # Local column
            ['id']  # Referenced column
        )

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('bank_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('bank_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_inventory_item_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
