"""Remove default_bank_id from User model

Revision ID: 697bed8c15d6
Revises: 6d2415abb760
Create Date: 2025-05-10 12:21:43.024636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697bed8c15d6'
down_revision = '6d2415abb760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_default_bank_id', type_='foreignkey')
        batch_op.drop_column('default_bank_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_bank_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_default_bank_id', 'bank', ['default_bank_id'], ['id'])

    # ### end Alembic commands ###
