"""Initial migration

Revision ID: 6d2415abb760
Revises: 
Create Date: 2025-05-10 11:52:22.764694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2415abb760'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('balance', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('expense',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('paid', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('inventory_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('brand', sa.String(length=100), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('sku', sa.String(length=50), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('cost', sa.Float(), nullable=False),
                    sa.Column('selling_price', sa.Float(), nullable=False),
                    sa.Column('color', sa.String(length=50), nullable=True),
                    sa.Column('size', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('sku')
                    )
    op.create_table('transaction',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(length=20), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('description', sa.String(
                        length=200), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.Column('bank_id', sa.Integer(), nullable=False),
                    sa.Column('expense_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['bank_id'], ['bank.id'], name='fk_transaction_bank_id'),
                    sa.ForeignKeyConstraint(
                        ['expense_id'], ['expense.id'], name='fk_transaction_expense_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=80), nullable=False),
                    sa.Column('password', sa.String(
                        length=200), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_default_bank_id', type_='foreignkey')
        batch_op.drop_column('default_bank_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction')
    op.drop_table('inventory_item')
    op.drop_table('expense')
    op.drop_table('bank')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_bank_id',
                            sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_user_default_bank_id', 'bank', ['default_bank_id'], ['id']
        )
    # ### end Alembic commands ###
